GET http://localhost:8000/api/users

###

POST http://localhost:8000/api/users
Content-Type: application/json

{
  "Name": "Ali KARABAY",
  "Email": "test@mail.com"
}

###

DELETE http://localhost:3000/api/users/1
Content-Type: application/json
